repository:
  private: true
  is_template: false
  default_branch: main

  has_issues: true
  has_wiki: false
  has_downloads: false
  has_projects: true

  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true

labels:
  - name: bug
    description: Something is broken
    color: '#CC0000'
  - name: chore
    description: Repository or code maintenance
    color: '#f2df8c'
  - name: dependencies
    color: '#70f9e0'
    description: Update dependencies
  - name: documentation
    description: Change in the documentation
    color: '#6cb524'
  - name: do-not-merge
    description: This PR should not be merged
    color: '#ed622f'
  - name: feature
    description: New feature or change to an existing feature
    color: '#336699'

teams:
  - name: admins
    permission: admin

branches:
  - name: main
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        dismissal_restrictions: {}
      required_status_checks:
        strict: true
        contexts: []
      required_signatures: true
      enforce_admins: null
      restrictions: null
